version: 2.1

# Define jobs for the project
jobs:
  build:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Run Main1.py
          command: python Main1.py

  test:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Run Test.py
          command: python Test.py

# Define workflows that specify job execution order
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
