
version: 2.1
# Define a job we want to run for this projectjobs:
jobs:
 build:
    docker:
      -image: python
      steps:
         -checkout
         -run:python Main1.py 
     test:
       docker:
          -image:python
       steps:
         -checkout
         -run:python Test.py
workflows:
 build_and_test:
    jobs:
     -build
     -test
